converted help page 'showing' flag to BehaviorSubject
omridevk/ng-keyboard-shortcuts pull request #140
Opened 2022-08-15 21:47 UTC by abritabroad

I had issues in my project where the help screen wasn't popping up until extra keys were pressed. Converting a flag from boolean to BehaviorSubject<boolean> and referencing it with an async pipe fixed my issue.

2022-08-15 21:49 UTC, omridevk commented
@abritabroad 
Thank you very much!
Can you give a small reproduction case? because I couldn't reproduce it on my playground env.

2022-08-15 21:55 UTC, abritabroad commented
Yeah, I couldn't repro it in the standalone either. Our project has a bunch of  other keyboard listeners that may interfere with it and may be affected by push strategy. I'll see if I can duplicate it with push strategy in the playground.

2022-08-15 22:56 UTC, abritabroad commented
ok, If you add the 'changeDetection' line to the AppComponent decorator you can reproduce the issue.

`@Component({
    selector: "ng-keyboard-shortcuts-demo-app",
    templateUrl: "./app.component.html",
    styleUrls: ["./app.component.scss"],
    changeDetection: ChangeDetectionStrategy.OnPush
})
export class AppComponent implements AfterViewInit {
`

2022-08-16 07:44 UTC, omridevk requested changes

2022-08-16 07:44 UTC, omridevk commented on libs/ng-keyboard-shortcuts/src/lib/ng-keyboard-shortcuts-help.component.ts
> +    showing$: BehaviorSubject<boolean> = new BehaviorSubject(false);
no need the typing, there's type inference.

2022-08-16 15:44 UTC, merged